### PR TITLE
Add support for moving items up/down 10 rows and to top or bottom of …

### PR DESCRIPTION
**Pull request by snarkophilus**
…a reading list.

### CODE REVIEW

**Comment by JimmXinu** [comment]
Found a few bugs.

If I select several books and click up/down 10 or beginning/end, I end up with blank rows appearing in the list.  Here's a simple way to see it (Win10, Calibre 64 bit):
1. Add four items to an empty list
1. Edit List
1. Select top 3 items
1. Click 'Move to bottom'
1. Watch empty rows appear
1. Click  'Move to bottom' or 'Move to top' more times to see more weirdness.

Looping on `move_rows_up/down()` is inelegant and inefficient for large lists, especially with large selections.  I had it hang for several seconds with less than a 1000 entry list.  Many calibre users have libraries of 10s of thousands.

There's a comment in `move_rows_up(self)` that says:
```
        # Workaround for strange selection bug in Qt which "alters" the selection
        # in certain circumstances which meant move down only worked properly "once"
```
I wonder if that's part of it?

**Comment by snarkophilus** [comment]
For the first bug, blank rows appearing, I can reproduce that - probably just need to add a bounds check?  This was obviously a case I didn't check.  Ta, will look into this.

For the second bug/comment, yes, looping is inefficient.  I see a small delay with my current 300ish list.  This was the least invasive way to implement this.  I'd also wager than people with a 1000 entry list wouldn't move items or selections of items through lists, at least not without breaking their mouse button :).

Last - I think I should have created a branch then applied the patch in my local git repo?  Still new git.

**Comment by snarkophilus** [comment]
Jim- for the first bug, I can reproduce the problem with the existing (unmodified) plugin with the same steps, except clicking on the down arrow button repeatedly.  With four books in a list , the first click moves the top three items down to the bottom, the following clicks then insert a blank row per click.

**Comment by JimmXinu** [comment]
So it does.  Joy.

I think I figured it out and pushed a fix: f9ab4946b4c687aa81c2c98984dff36386423157

You want to try that with your code?

**Comment by snarkophilus** [comment]
> So it does. Joy.
> 
> I think I figured it out and pushed a fix: [f9ab494](https://github.com/JimmXinu/JimmsOtherCalibrePlugins/commit/f9ab4946b4c687aa81c2c98984dff36386423157)
> 
> You want to try that with your code?

Yep, that works for me!  Thanks.

**Comment by JimmXinu** [comment]
I'm not sure why the commit has a different number, but I did incorporate this: 6debdf50a31755ae0e4ead67b4e518b92b6f256c

**Pull request closed without merging**
